---
- hosts: dev
  sudo: yes
  tasks:
   - name: Install add-apt-repostory
     become: yes
     apt: name=software-properties-common state=latest

   - name: Add Oracle Java Repository
     become: yes
     apt_repository: repo='ppa:webupd8team/java'
   - name: Accept Java 8 License
     become: yes
     debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

   - name: Install Oracle Java 8
     become: yes
     apt: name={{item}} state=latest
     with_items:
       - oracle-java8-installer
       - ca-certificates
       - oracle-java8-set-default

   - name: Create Folder
     file:
      path: /home/ubuntu/tomcat1
      state: directory
      mode: 0755
      
      
      

   - name: Download Tomcat
     get_url: url=https://www-eu.apache.org/dist/tomcat/tomcat-9/v9.0.13/bin/apache-tomcat-9.0.13.tar.gz dest=/home/ubuntu/tomcat1

   - name: Extract archive
     unarchive: src=/home/ubuntu/tomcat/apache-tomcat-9.0.13.tar.gz dest=/home/ubuntu/tomcat1 remote_src=yes
  
   - name: Download Application
     get_url: url=https://s3.us-east-2.amazonaws.com/krishbucket12/petclinic.war dest=/home/ubuntu

   - name: start apache-tomcat-9.0.13
     command: /home/ubuntu/tomcat/apache-tomcat-9.0.13.tar.gz/bin/startup.sh

   - name: copy Petclinic.war
     shell: cp /home/ubuntu/petclinic.war /home/ubuntu/tomcat/apache-tomcat-9.0.13.tar.gz/webapps/

   - name: stop apache-tomcat-9.0.13
     command: /home/ubuntu/tomcat/apache-tomcat-9.0.13.tar.gz/bin/shutdown.sh
   
   - name: start apache-tomcat-9.0.13
     command: /home/ubuntu/apache-tomcat-9.0.13.tar.gz/bin/startup.sh
